[package]
authors = ["armesingular <arme@singular.live>"]
edition = "2018"
name = "nilakantha_series"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.1.2"
